package com.skyler.catalogo.domain.descontos.enums;

public enum DescontoTipo {
    DESCONTO_FRETE,
    DESCONTO_GENERICO_CARRINHO,
    DESCONTO_SIMPLES_PRODUTO,
    DESCONTO_SIMPLES_TERMO,
    DESCONTO_PECA_MAIOR_VALOR,
    DESCONTO_PECA_MENOR_VALOR,
    DESCONTO_PROGRESSIVO
}
